=pod
$sir = 'accgcggttcgtactgaggaa';
$pos1 = '3';
$pos2 = '8';
$sir_nou = substr ($sir, $pos1, $pos2);
print $sir_nou;
=cut
use lib;
use strict;
use warnings;
use v5.10;

my $origin = 'NANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNGGGGGGGGGGGGGGGGGGGGGLLLLLLLLLLLLLLLLLNNNNNNNNNNNNNNNNNNNNNHHHHHHHHHHHHNNNNNNNNNNNNNJJJJJJJJJJJJJJNNNNNNNNNNNNNNNFFFFFFFFFFFFFFFFFFFFNNNNNNNNNNNNNNNNNNNNNNNAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNGATCACAGAGGCTGGGCTGCTCCCCACCCTCTGCACACCTCCTGCTTCTAACAGCAGAGCTGCCAGGCCAGGCCCTCAGGCAAGGGCTCTGAAGTCAGGGTCACCTACTTGCCAGGGCCGATCTTGGTGCCATCCAGGGGGCCTCTACAAGGATAATCTGACCTGCAGGGTCGAGGAGTTGACGGTGCTGAGTTCCCTGCACTCTCAGTAGGGACAGGCCCTATGCTGCCACCTGTACATGCTATCTGAAGGACAGCCTCCAGGGCACACAGAGGATGGTATTTACACATGCACACATGGCTACTGATGGGGCAAGCACTTCACAACCCCTCATGATCACGTGCAGCAGACAATGTGGCCTCTGCAGAGGGGGAACGGAGACCGGAGGCTGAGACTGGCAAGGCTGGACCTGAGTGTCGTCACCTAAATTCAGACGGGGAACTGCCCCTGCACATAGTGAACGGCTCACTGAGCAAACCCCGAGTCCCGACCACCGCCTCAGTGTGGTCTAGCTCCTCACCTGCTTCCATCCTCCCTGGT
';
my @CDS = ('CDS             join(complement(2..17),
                     complement(28..81),complement(100..151),
                     complement(275..282),complement(340..5560))
                     /gene="ENSG00000141934.10"
                     /protein_id="ENSP00000329697.1"
                     /note="transcript_id=ENST00000327790.7"
                     /db_xref="CCDS:CCDS12024"
                     /db_xref="Uniprot/SWISSPROT:O43688"
                     /db_xref="RefSeq_peptide:NP_808211"
                     /db_xref="RefSeq_mRNA:NM_177543"
                     /db_xref="UCSC:ENST00000327790.7"
                     /db_xref="HPA:HPA055540"
                     /db_xref="HPA:55540"
                     /db_xref="EMBL:AC016588"
                     /db_xref="EMBL:AF035959"
                     /db_xref="EMBL:AF047760"
                     /db_xref="EMBL:AF056083"
                     /db_xref="EMBL:BC002806"
                     /db_xref="EMBL:BT007021"
                     /db_xref="GO:0004721"
                     /db_xref="GO:0005515"
                     /db_xref="GO:0005886"
                     /db_xref="GO:0005887"
                     /db_xref="GO:0006470"
                     /db_xref="GO:0006644"
                     /db_xref="GO:0007165"
                     /db_xref="GO:0008195"
                     /db_xref="GO:0008195"
                     /db_xref="GO:0008195"
                     /db_xref="GO:0008195"
                     /db_xref="GO:0016020"
                     /db_xref="GO:0016020"
                     /db_xref="GO:0016021"
                     /db_xref="GO:0016787"
                     /db_xref="GO:0016791"
                     /db_xref="GO:0030148"
                     /db_xref="GO:0042577"
                     /db_xref="GO:0046839"
                     /db_xref="HGNC_trans_name:PLPP2-202"
                     /db_xref="protein_id:AAC15968"
                     /db_xref="protein_id:AAC25666"
                     /db_xref="protein_id:AAC32104"
                     /db_xref="protein_id:AAH02806"
                     /db_xref="protein_id:AAP35667"
                     /db_xref="KEGG_Enzyme:00561+3.1.3.4"
                     /db_xref="KEGG_Enzyme:00564+3.1.3.4"
                     /db_xref="KEGG_Enzyme:00565+3.1.3.4"
                     /db_xref="KEGG_Enzyme:00600+3.1.3.4"
                     /db_xref="Reactome:R-HSA-1430728"
                     /db_xref="Reactome:R-HSA-1660661"
                     /db_xref="Reactome:R-HSA-428157"
                     /db_xref="Reactome:R-HSA-556833"
                     /db_xref="UniParc:UPI0000168654"
                     /translation="MGVARGPGSRGQHPPPRQQEVCAEGPRARLHPAPPGLGASLPFA
                     ILTLVNAPYKRGFYCGDDSIRYPYRPDTITHGLMAGVTITATVILVSAGEAYLVYTDR
                     LYSRSDFNNYVAAVYKVLGTFLFGAAVSQSLTDLAKYMIGRLRPNFLAVCDPDWSRVN
                     CSVYVQLEKVCRGNPADVTEARLSFYSGHSSFGMYCMVFLALYVQARLCWKWARLLRP
                     TVQFFLVAFALYVGYTRVSDYKHHWSDVLVGLLQGALVAALTVCYISDFFKARPPQHC
                     LKEEELERKPSLSLTLTLGEADHNHYGYPHSSS"',
	  'CDS            5570..6000
                     /gene="ENSG00000176695.8"
                     /protein_id="ENSP00000467301.1"
                     /note="transcript_id=ENST00000585993.3"
                     /db_xref="CCDS:CCDS32854"
                     /db_xref="Uniprot/SWISSPROT:Q8NGA8"
                     /db_xref="RefSeq_peptide:NP_001005240"
                     /db_xref="RefSeq_mRNA:NM_001005240"
                     /db_xref="Uniprot/SPTREMBL:A0A126GWN0"
                     /db_xref="UCSC:ENST00000585993.3"
                     /db_xref="EMBL:AB065917"
                     /db_xref="EMBL:BC136848"
                     /db_xref="EMBL:BC136867"
                     /db_xref="EMBL:KP290649"
                     /db_xref="GO:0004888"
                     /db_xref="GO:0004930"
                     /db_xref="GO:0004930"
                     /db_xref="GO:0004930"
                     /db_xref="GO:0004984"
                     /db_xref="GO:0004984"
                     /db_xref="GO:0005886"
                     /db_xref="GO:0005886"
                     /db_xref="GO:0007165"
                     /db_xref="GO:0007186"
                     /db_xref="GO:0007186"
                     /db_xref="GO:0007186"
                     /db_xref="GO:0007186"
                     /db_xref="GO:0007608"
                     /db_xref="GO:0016020"
                     /db_xref="GO:0016021"
                     /db_xref="GO:0016021"
                     /db_xref="GO:0016021"
                     /db_xref="GO:0050896"
                     /db_xref="GO:0050911"
                     /db_xref="HGNC_trans_name:OR4F17-202"
                     /db_xref="protein_id:AAI36849"
                     /db_xref="protein_id:AAI36868"
                     /db_xref="protein_id:ALI87807"
                     /db_xref="protein_id:BAC06132"
                     /db_xref="Reactome:R-HSA-162582"
                     /db_xref="Reactome:R-HSA-372790"
                     /db_xref="Reactome:R-HSA-381753"
                     /db_xref="Reactome:R-HSA-388396"
                     /db_xref="Reactome:R-HSA-418555"
                     /db_xref="UniParc:UPI0000041E2A"
                     /translation="MVTEFIFLGLSDSQGLQTFLFMLFFVFYGGIVFGNLLIVITVVS
                     DSHLHSPMYFLLANLSLIDLSLSSVTAPKMITDFFSQRKVISFKGCLVQIFLLHFFGG
                     SEMVILIAMGFDRYIAICKPLHYTTIMCGNACVGIMAVAWGIGFLHSVSQLAFAVHLP
                     FCGPNEVDSFYCDLPRVIKLACTDTYRLDIMVIANSGVLTVCSFVLLIISYTIILMTI
                     QHRPLDKSSKALSTLTAHITVVLLFFGPCVFIYAWPFPIKSLDKFLAVFYSVITPLLN
                     PIIYTLRNKDMKTAIRQLRKWDAHSSVKF"', 'CDS            6001..6002
                     /gene="ENSG00000176695.8"
                     /protein_id="ENSP00000467301.1"
                     /note="transcript_id=ENST00000585993.3"
                     /db_xref="CCDS:CCDS32854"
                     /db_xref="Uniprot/SWISSPROT:Q8NGA8"
                     /db_xref="RefSeq_peptide:NP_001005240"');

my $nucleotide = undef;
my $lim_inf = undef;
my $lim_sup = undef;
my $range = undef;

#foreach (@CDS)
#{
#do
#{print $nucleotide
#}
#while 
#$nucleotide = substr($origin, $lim_inf, $lim_sup);

	#if ($_ = ~ /\(\d+\.\.\d+\)/gm) #pt CDS cu complement
	#{$range = $& #$range se incarca cu match
	
	#$lim_inf =~ /(?<=\()\d*?(?=\.)/g;
	#$lim_sup =~ /(?<=\.)\d*?(?=\))/g;
	#}
	#do 
	#{$range = $&;
	#given ($range)
	#			{
	#			when ($_ =~ /(?<= )\d*?(?=\.)/g)
	#			{$lim_inf = $&;}
	#			when ($_ =~ /(?<=\.)\d*?(?= )/g)
	#			{$lim_sup = $&;}
	#			}
	#}
	#while ($_ =~ /\d+\.\.\d+/gm); #gaseste tot 2..17
	
	
	
#}
foreach (@CDS)
{
while (print $nucleotide)
	{while ( $nucleotide = substr($origin, $lim_inf, $lim_sup) )
		{do 
			{$range = $&;
				foreach ($range)
				{
				do 
				{$lim_inf = $&}
				while ($_ =~ /(?<= )\d*?(?=\.)/g);
				do 
				{$lim_sup = $&}
				while($_ =~ /(?<=\.)\d*?(?= )/g)
				}
			}
		while ($_ = ~ /\(\d+\.\.\d+\)/gm)
		}
		
			
			#$lim_inf =~/(?<=\()\d*?(?=\.)/g;
			#$lim_sup =~ /(?<=\.)\d*?(?=\))/g;
			#print $lim_inf;
			#print $lim_sup;}
		
	}
}
print $range;
print 'azi';
#while			
								
								
				
				#foreach ($range)
				#{
				#do 
				#{$lim_inf = $&;}
				#while ($_ =~ /(?<= )\d*?(?=\.)/g)
								#do 
				#{$lim_sup = $&;}
				#while ($_ =~ /(?<=\.)\d*?(?= )/g)
			
	
			
				
			
	

